/**
 * Copyright (c) CMG Ltd All rights reserved.
 *
 * This software is the confidential and proprietary information of CMG
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with CMG.
 */

package com.cmg.maven.plugins.cmgium;

import junit.framework.Test;
import junit.framework.TestSuite;

/** 
 * This class is generated by Cmgium maven plugin
 * 
 * @Creator Cmgium Generator
 */

public class AllTests {

	public static Test suite() throws Exception {
		
		TestSuite suite = new TestSuite(AllTests.class.getName());
		System.out.println("Start suite test");
		//$JUnit-BEGIN$
		suite.addTestSuite(TestCase1.class);
		suite.addTestSuite(TestCase2.class);
		suite.addTestSuite(TestScriptMojoTest.class);
	
		//$JUnit-END$
	
		return suite;
	}

}
